### ISSUE TITLE
On Catalina and Big Sur，can't connect to the internet.

### ISSUE THREAD

**Issue by d-weed** [oNuRix/-Acer-Swift-3-SF314-56-Opencore-#1]
Is this EFI file only available on Monterey? On Catalina and Big Sur, the wifi icon doesn't show up after boot, and the usb card doesn't work, can't connect to the internet.

**Comment by oNuRix** [comment]
You muss select in opencore configurator airportitlw for which version you will boot and disable another airportitlw.

**Comment by d-weed** [comment]
it works, thank you

**Comment by oNuRix** [comment]
You welcome
